### PR TITLE
Fix dictionary parsing

### LINKED ISSUE #4: Handle typed dictionaries
4.4-dev has implemented support for typed dictionaries: 
https://godotengine.org/article/dev-snapshot-godot-4-4-dev-2/#typed-dictionaries

4.4 hasn't had an official release yet, but when it does, this will start showing up in resources and scenes. Syntax is similar to typed Arrays: `Dictionary[<keytype>, <valtype>]`. An example of it being used in a resource would be:
```ini
[resource]
test_dict = Dictionary[int, String]({ 1: "first value", 2: "second value", 3: "etc" })
```

### LINKED ISSUE #5: Dictionary parser only allows for strings as keys
The parser currently only allows for strings as keys in dictionaries. However, dictionaries in Godot can have any variant as a key. For example, this is a valid resource:
```ini
[resource]
test_untyped_dict = {
    1: "first value",
    { 1: 5.2 }: "second value",
    [0, 1, 2]: "third value",
    PackedStringArray("foo", "bar", "baz"): "fourth value"
}
```

The parser currently errors out on encountering anything other than a string.

### PR DESCRIPTION
**Pull request by nikitalita**
Fixes #4
Fixes #5

* changed `pair` from `seq($.string, ":", $._value)` to `seq($._value, ":", $._value)`
* added     `objPair: ($) => seq($.string, ":", $._value)`
* changed `arguments` from `seq("(", optional(commaSep1(choice($._value, $.pair))), ")")` to `seq("(", optional(commaSep1(choice($._value, $.objPair))), ")")`

This may break compatibility for current users of this package because of the arguments change. We could potentially just leave arguments as is to maintain compatibility if necessary.

### CODE REVIEW

**Comment by PrestonKnopp** [comment]
What do you think about reusing `$.pair` instead of a separate `$.objPair` rule?

**Comment by nikitalita** [comment]
I think it would be fine; we would rarely encounter Objects that are directly instanced in resources anyway

**Comment by PrestonKnopp** [comment]
Okay, great. Will you remove the `objPair` rule? Then I'll merge this PR.

**Comment by nikitalita** [comment]
Ok, done.

**Comment by PrestonKnopp** [comment]
Awesome, thank you for working on this!

**Pull request merged**
